class MonitorType:
    CPU = "cpu"
    CPU_PER_CORE = "cpu per core"
    GPU = "gpu"
    Memory = "memory"
    Swap = "swap"
    Downlink = "downlink"
    Uplink = "uplink"
    Home_usage = "home usage"
    Root_usage = "root usage"
    CPU_PRESSURE = "cpu pressure"
    MEMORY_PRESSURE = "memory pressure"
    IO_PRESSURE = "io pressure"
