class PreferenceKeys:
    THEME = "general.theme"
    LAYOUT = "general.layout"
    SMOOTH_GRAPH = "general.smooth_graph"
    CPU_MONITOR_ENABLED = "cpu_monitor.enabled"
    CPU_PER_CORE_MONITOR_ENABLED = "cpu_per_core_monitor.enabled"
    GPU_MONITOR_ENABLED = "gpu_monitor.enabled"
    MEMORY_MONITOR_ENABLED = "memory_monitor.enabled"
    SWAP_MONITOR_ENABLED = "swap_monitor.enabled"
    DOWNLINK_MONITOR_ENABLED = "downlink_monitor.enabled"
    UPLINK_MONITOR_ENABLED = "uplink_monitor.enabled"
    HOME_USAGE_MONITOR_ENABLED = "home_usage_monitor.enabled"
    ROOT_USAGE_MONITOR_ENABLED = "root_usage_monitor.enabled"
